# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_title = QtWidgets.QLabel(self.centralwidget)
        self.main_title.setGeometry(QtCore.QRect(60, 40, 671, 81))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(26)
        self.main_title.setFont(font)
        self.main_title.setObjectName("main_title")
        self.StockFinderButton = QtWidgets.QPushButton(self.centralwidget)
        self.StockFinderButton.setGeometry(QtCore.QRect(310, 200, 131, 51))
        self.StockFinderButton.setObjectName("StockFinderButton")
        self.PortfolioButton = QtWidgets.QPushButton(self.centralwidget)
        self.PortfolioButton.setGeometry(QtCore.QRect(310, 300, 131, 51))
        self.PortfolioButton.setObjectName("PortfolioButton")
        self.LearningCentreButton = QtWidgets.QPushButton(self.centralwidget)
        self.LearningCentreButton.setGeometry(QtCore.QRect(310, 400, 131, 51))
        self.LearningCentreButton.setObjectName("LearningCentreButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.main_title.setText(_translate("MainWindow", "Trading Simulator For Beginners 101"))
        self.StockFinderButton.setText(_translate("MainWindow", "Log-in"))
        self.PortfolioButton.setText(_translate("MainWindow", "Sign-up"))
        self.LearningCentreButton.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
